os: osx
osx_image: xcode9.4

language: c++

sudo: required

services:
    - docker

before_install: travis/before-install-osx.sh

script:
    - travis/build-osx.sh
    - travis/build-osx-node.sh

notifications:
  email: false
